### ISSUE TITLE
Inc_color renamed to util_color

### ISSUE THREAD

**Issue by trialsofnewcastle** [trialsofnewcastle/Trials-Of-Newcastle#132]
Main func depreciated to fix the way everything broke with updates. Need to continue removing the depreciated func calls from the mod.

**Comment by milliorn** [comment]
https://github.com/nwn-dotnet/NWN.Managed/blob/fcfbf40fee6772485af1fcccd2d61a3c571407af/src/main/NWN/API/Color.cs

**Comment by trialsofnewcastle** [comment]
> https://github.com/nwn-dotnet/NWN.Managed/blob/fcfbf40fee6772485af1fcccd2d61a3c571407af/src/main/NWN/API/Color.cs

Is that useable inside nwscript? Or would I need to migrate all of the other systems that I am using first?

The script is massively integrated into almost every system in the module and has been one of the many things that Beamdog updates have broken beyond repair.

**Comment by trialsofnewcastle** [comment]
I have depreciated the broken func: ```string Color_Text(string ColorCode, string sText);```

The new one that I am migrating to is: ```string Color_ConvertString(string sString, string sRGB);```

It is a wrapper with some const stuff for ease for a Bioware RBG call. It is also totally compatible with the code that a number of the NWNXEE team members use in their projects to make some stuff more easily integrated.

https://github.com/trialsofnewcastle/Trials-Of-Newcastle-Dev/blob/master/src/module/nss/util_color.nss
