### ISSUE TITLE
Lino needs to be renamed and debugged

### ISSUE THREAD

**Issue by trialsofnewcastle** [trialsofnewcastle/Trials-Of-Newcastle#19]
Ported to EE this evening. His table and WP are placed, convo is in zzD already. No testing is done and not set to spawn. His model is being used by Spencer so he should be renamed and appearance swapped. He might use the old Aley Bross model.

**Comment by trialsofnewcastle** [comment]
Bugs remain problematic. Looking at removing thelistener feature and running off onchat. Renamed to Inga. Oddly there is now a strange bug where Inga and Belle share the same wardrobe no matter which one is changed.

**Comment by milliorn** [comment]
Possible they share the same resref or tagname (Inga/Belle)?

**Comment by trialsofnewcastle** [comment]
@milliorn Different resrefs and tags. It is totally wierd. I have never seen this in toolset before.

**Comment by trialsofnewcastle** [comment]
This may be irrelevant with the options via new nwnx chat. More work needs to be done to investigate this.

**Comment by trialsofnewcastle** [comment]
Lino removed as he is now obsolete.
