### ISSUE TITLE
Dev Request Subrace Books

### ISSUE THREAD

**Issue by DefiantShade** [trialsofnewcastle/Trials-Of-Newcastle#39]
Could we allow Subrace books to convert current PC with subrace assigned to enhanced version?

For example : PC is subrace  Drow. Use book that unlocks "Drow Noble" , to essentially upgrade the PC to that subrace.  Since the book unlocks the subrace itself, finding a second book and using it to accomplish this would be fair.

**Comment by trialsofnewcastle** [comment]
Please also reflect, in all subrace work, that the intention is for the module to be human-centric.
