### ISSUE TITLE
Convince "@The Capulet" in Discord that he wants to be our dedicated map designer for this project and fully join the team.

### ISSUE THREAD

**Issue by trialsofnewcastle** [trialsofnewcastle/Trials-Of-Newcastle#62]

**Comment by thev88** [comment]
Isent this better for someone who has talked with them in the past? Kinda odd for a 'random' to pop in and start trying this.

**Comment by trialsofnewcastle** [comment]
I'm finding it impossible to make contact at present. Might be a timezone thing. Not sure.

Alternatively we need another exceedingly talented area designer who can make stuff from specs. 

This could in theory be one of the non Newcastle builders that EinHerjer mentined
